;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        delete-horizontal-space
        indent-region
        kill-region
        markdown-cycle
        ))

(setq mc/cmds-to-run-once
      '(
        next-buffer
        sh-assignment
        ))
