;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-semi&comma
<<<<<<< HEAD
        c-electric-slash
        delete-horizontal-space
        indent-region
        kill-region
        markdown-cycle
=======
        delete-horizontal-space
        indent-for-tab-command
        indent-region
        kill-region
>>>>>>> 9bc3e14a5b9e92eb42dd61eef160db000b8fb8ac
        ))

(setq mc/cmds-to-run-once
      '(
        next-buffer
        sh-assignment
        ))
